from __future__ import annotations

from datetime import timedelta

from sqlalchemy import select
from sqlalchemy.orm import Session

from ...enums import RoleCode, TicketMainStatus, TicketPriority, TicketSubStatus
from .models import Ticket, TicketAction, TicketComment
from ...security import utcnow

CATEGORY_NAMES = {
    "intrusion": "入侵检测",
    "network": "网络攻击",
    "data": "数据安全",
    "endpoint": "终端安全",
    "phishing": "网络钓鱼",
}

POOL_CODES = {"T1_POOL", "T2_POOL", "T3_POOL"}

TICKET_SEED_DATA = [
    {
        "id": 100182,
        "title": "横向移动预警：域账号异常访问多台办公终端",
        "description": "SIEM 捕获到同一域账号在 12 分钟内访问多台办公终端并伴随横向认证尝试，已完成初判，等待升级确认。",
        "category_id": "intrusion",
        "category_name": "入侵检测",
        "source": "SIEM",
        "priority": TicketPriority.P1.value,
        "risk_score": 92,
        "main_status": TicketMainStatus.IN_PROGRESS.value,
        "sub_status": TicketSubStatus.ESCALATION_PENDING_CONFIRM.value,
        "created_by": "系统规则",
        "created_by_user_id": "user-admin",
        "customer_user_id": None,
        "assigned_to": "Admin",
        "assigned_to_user_id": "user-admin",
        "current_pool_code": None,
        "responsibility_level": "T2",
        "response_deadline_at": utcnow() + timedelta(hours=1),
        "resolution_deadline_at": utcnow() + timedelta(hours=4),
        "responded_at": utcnow() - timedelta(minutes=30),
        "response_timeout_at": None,
        "resolved_at": None,
        "resolution_timeout_at": None,
        "closed_at": None,
        "created_at": utcnow() - timedelta(hours=2),
        "updated_at": utcnow() - timedelta(minutes=12),
    },
    {
        "id": 100181,
        "title": "客户反馈：补充邮件钓鱼处置报告结论",
        "description": "客户要求在关闭前补充影响范围与修复建议，当前已处置完成，等待最终关闭。",
        "category_id": "phishing",
        "category_name": "网络钓鱼",
        "source": "CUSTOMER",
        "priority": TicketPriority.P2.value,
        "risk_score": 63,
        "main_status": TicketMainStatus.RESOLVED.value,
        "sub_status": TicketSubStatus.NONE.value,
        "created_by": "Customer",
        "created_by_user_id": "user-customer",
        "customer_user_id": "user-customer",
        "assigned_to": "Admin",
        "assigned_to_user_id": "user-admin",
        "current_pool_code": None,
        "responsibility_level": "T2",
        "response_deadline_at": utcnow() - timedelta(days=1, hours=4),
        "resolution_deadline_at": utcnow() - timedelta(hours=6),
        "responded_at": utcnow() - timedelta(days=1, hours=5),
        "response_timeout_at": None,
        "resolved_at": utcnow() - timedelta(hours=2),
        "resolution_timeout_at": None,
        "closed_at": None,
        "created_at": utcnow() - timedelta(days=1, hours=8),
        "updated_at": utcnow() - timedelta(hours=2),
    },
    {
        "id": 100177,
        "title": "夜班值守：终端恶意软件待 T2 池领取",
        "description": "EDR 在夜班期间连续上报可疑落地动作，当前工单已进入 T2_POOL，等待内部人员领取。",
        "category_id": "endpoint",
        "category_name": "终端安全",
        "source": "EDR",
        "priority": TicketPriority.P2.value,
        "risk_score": 74,
        "main_status": TicketMainStatus.WAITING_RESPONSE.value,
        "sub_status": TicketSubStatus.NONE.value,
        "created_by": "系统规则",
        "created_by_user_id": "user-analyst",
        "customer_user_id": None,
        "assigned_to": None,
        "assigned_to_user_id": None,
        "current_pool_code": "T2_POOL",
        "responsibility_level": "T2",
        "response_deadline_at": utcnow() + timedelta(minutes=38),
        "resolution_deadline_at": utcnow() + timedelta(hours=7),
        "responded_at": None,
        "response_timeout_at": None,
        "resolved_at": None,
        "resolution_timeout_at": None,
        "closed_at": None,
        "created_at": utcnow() - timedelta(minutes=40),
        "updated_at": utcnow() - timedelta(minutes=22),
    },
    {
        "id": 100169,
        "title": "主机异常登录：响应 SLA 已超时",
        "description": "检测到堡垒机来源的异常登录爆发，当前尚未补响应，主状态保持 RESPONSE_TIMEOUT。",
        "category_id": "intrusion",
        "category_name": "入侵检测",
        "source": "SIEM",
        "priority": TicketPriority.P1.value,
        "risk_score": 87,
        "main_status": TicketMainStatus.RESPONSE_TIMEOUT.value,
        "sub_status": TicketSubStatus.NONE.value,
        "created_by": "系统规则",
        "created_by_user_id": "user-admin",
        "customer_user_id": None,
        "assigned_to": "Analyst",
        "assigned_to_user_id": "user-analyst",
        "current_pool_code": None,
        "responsibility_level": "T1",
        "response_deadline_at": utcnow() - timedelta(hours=3),
        "resolution_deadline_at": utcnow() + timedelta(hours=2),
        "responded_at": None,
        "response_timeout_at": utcnow() - timedelta(hours=2),
        "resolved_at": None,
        "resolution_timeout_at": None,
        "closed_at": None,
        "created_at": utcnow() - timedelta(hours=5),
        "updated_at": utcnow() - timedelta(hours=1, minutes=20),
    },
    {
        "id": 100161,
        "title": "客户系统故障排查单",
        "description": "客户侧应用访问异常已恢复，当前仅保留关闭态记录供后续复盘和 Reopen 使用。",
        "category_id": "network",
        "category_name": "网络攻击",
        "source": "CUSTOMER",
        "priority": TicketPriority.P3.value,
        "risk_score": 41,
        "main_status": TicketMainStatus.CLOSED.value,
        "sub_status": TicketSubStatus.NONE.value,
        "created_by": "Customer",
        "created_by_user_id": "user-customer",
        "customer_user_id": "user-customer",
        "assigned_to": "Admin",
        "assigned_to_user_id": "user-admin",
        "current_pool_code": None,
        "responsibility_level": "T2",
        "response_deadline_at": utcnow() - timedelta(days=3),
        "resolution_deadline_at": utcnow() - timedelta(days=2, hours=18),
        "responded_at": utcnow() - timedelta(days=3, hours=1),
        "response_timeout_at": None,
        "resolved_at": utcnow() - timedelta(days=2, hours=20),
        "resolution_timeout_at": None,
        "closed_at": utcnow() - timedelta(days=2, hours=18),
        "created_at": utcnow() - timedelta(days=4),
        "updated_at": utcnow() - timedelta(days=2, hours=18),
    },
]

TICKET_ACTION_SEED_DATA = [
    {
        "id": "action-100182-created",
        "ticket_id": 100182,
        "action_type": "created",
        "actor_name": "System",
        "actor_role": None,
        "visibility": "PUBLIC",
        "content": "SIEM 规则命中后自动创建工单并推送给值班队列。",
        "from_status": None,
        "to_status": TicketMainStatus.WAITING_RESPONSE.value,
        "context": {},
        "created_at": utcnow() - timedelta(hours=2),
    },
    {
        "id": "action-100182-assigned",
        "ticket_id": 100182,
        "action_type": "assigned",
        "actor_user_id": "user-admin",
        "actor_name": "Admin",
        "actor_role": RoleCode.ADMIN.value,
        "visibility": "INTERNAL",
        "content": "工单升级至 T2 并分配给当前负责人处理。",
        "from_status": None,
        "to_status": None,
        "context": {"assignee": "Admin"},
        "created_at": utcnow() - timedelta(hours=1, minutes=40),
    },
    {
        "id": "action-100177-created",
        "ticket_id": 100177,
        "action_type": "created",
        "actor_name": "System",
        "actor_role": None,
        "visibility": "PUBLIC",
        "content": "夜班值守期间由 EDR 自动创建工单。",
        "from_status": None,
        "to_status": TicketMainStatus.WAITING_RESPONSE.value,
        "context": {},
        "created_at": utcnow() - timedelta(minutes=40),
    },
    {
        "id": "action-100177-pooled",
        "ticket_id": 100177,
        "action_type": "moved_to_pool",
        "actor_name": "Duty Manager",
        "actor_role": RoleCode.T2.value,
        "visibility": "PUBLIC",
        "content": "夜班负责人将工单投入 T2 池等待白班同事领取。",
        "from_status": None,
        "to_status": None,
        "context": {"pool": "T2_POOL"},
        "created_at": utcnow() - timedelta(minutes=28),
    },
    {
        "id": "action-100169-created",
        "ticket_id": 100169,
        "action_type": "created",
        "actor_name": "System",
        "actor_role": None,
        "visibility": "PUBLIC",
        "content": "堡垒机异常登录行为触发工单创建。",
        "from_status": None,
        "to_status": TicketMainStatus.WAITING_RESPONSE.value,
        "context": {},
        "created_at": utcnow() - timedelta(hours=5),
    },
    {
        "id": "action-100169-timeout",
        "ticket_id": 100169,
        "action_type": "status_change",
        "actor_name": "System",
        "actor_role": None,
        "visibility": "PUBLIC",
        "content": "响应 SLA 超时，主状态切换为 RESPONSE_TIMEOUT。",
        "from_status": TicketMainStatus.WAITING_RESPONSE.value,
        "to_status": TicketMainStatus.RESPONSE_TIMEOUT.value,
        "context": {},
        "created_at": utcnow() - timedelta(hours=2),
    },
    {
        "id": "action-100181-created",
        "ticket_id": 100181,
        "action_type": "created",
        "actor_name": "Customer",
        "actor_role": RoleCode.CUSTOMER.value,
        "visibility": "PUBLIC",
        "content": "客户提交补充报告请求。",
        "from_status": None,
        "to_status": TicketMainStatus.WAITING_RESPONSE.value,
        "context": {},
        "created_at": utcnow() - timedelta(days=1, hours=8),
    },
    {
        "id": "action-100181-resolved",
        "ticket_id": 100181,
        "action_type": "resolved",
        "actor_name": "Admin",
        "actor_role": RoleCode.ADMIN.value,
        "visibility": "PUBLIC",
        "content": "已完成报告补充并更新处置结论。",
        "from_status": TicketMainStatus.IN_PROGRESS.value,
        "to_status": TicketMainStatus.RESOLVED.value,
        "context": {},
        "created_at": utcnow() - timedelta(hours=2),
    },
    {
        "id": "action-100161-created",
        "ticket_id": 100161,
        "action_type": "created",
        "actor_name": "Customer",
        "actor_role": RoleCode.CUSTOMER.value,
        "visibility": "PUBLIC",
        "content": "客户发起网络故障排查工单。",
        "from_status": None,
        "to_status": TicketMainStatus.WAITING_RESPONSE.value,
        "context": {},
        "created_at": utcnow() - timedelta(days=4),
    },
    {
        "id": "action-100161-closed",
        "ticket_id": 100161,
        "action_type": "closed",
        "actor_name": "Admin",
        "actor_role": RoleCode.ADMIN.value,
        "visibility": "PUBLIC",
        "content": "故障恢复确认后关闭工单。",
        "from_status": TicketMainStatus.RESOLVED.value,
        "to_status": TicketMainStatus.CLOSED.value,
        "context": {},
        "created_at": utcnow() - timedelta(days=2, hours=18),
    },
]

TICKET_COMMENT_SEED_DATA = [
    {
        "id": "comment-100182-1",
        "ticket_id": 100182,
        "actor_user_id": "user-admin",
        "actor_name": "Admin",
        "actor_role": RoleCode.ADMIN.value,
        "visibility": "INTERNAL",
        "content": "已确认横向认证痕迹，正在等待升级对象确认接手。",
        "is_system": False,
        "created_at": utcnow() - timedelta(hours=1, minutes=12),
        "updated_at": utcnow() - timedelta(hours=1, minutes=12),
    },
    {
        "id": "comment-100177-1",
        "ticket_id": 100177,
        "actor_user_id": "user-analyst",
        "actor_name": "Analyst",
        "actor_role": RoleCode.T1.value,
        "visibility": "PUBLIC",
        "content": "夜班已经完成基础证据保全，白班同事可直接继续排查落地样本。",
        "is_system": False,
        "created_at": utcnow() - timedelta(minutes=18),
        "updated_at": utcnow() - timedelta(minutes=18),
    },
    {
        "id": "comment-100181-1",
        "ticket_id": 100181,
        "actor_user_id": "user-customer",
        "actor_name": "Customer",
        "actor_role": RoleCode.CUSTOMER.value,
        "visibility": "PUBLIC",
        "content": "请在最终报告中补充业务影响范围和建议动作。",
        "is_system": False,
        "created_at": utcnow() - timedelta(hours=3),
        "updated_at": utcnow() - timedelta(hours=3),
    },
]


def seed_tickets(db: Session) -> None:
    existing_ids = set(db.scalars(select(Ticket.id)).all())
    for payload in TICKET_SEED_DATA:
        if payload["id"] in existing_ids:
            continue
        db.add(Ticket(**payload))
    db.commit()
    seed_ticket_supporting_records(db)


def seed_ticket_supporting_records(db: Session) -> None:
    existing_action_ids = set(db.scalars(select(TicketAction.id)).all())
    for payload in TICKET_ACTION_SEED_DATA:
        if payload["id"] in existing_action_ids:
            continue
        db.add(TicketAction(**payload))

    existing_comment_ids = set(db.scalars(select(TicketComment.id)).all())
    for payload in TICKET_COMMENT_SEED_DATA:
        if payload["id"] in existing_comment_ids:
            continue
        db.add(TicketComment(**payload))

    db.commit()
